// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package gatewaymsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ////////////////////////////////////////////////////////////////////
// 心跳类
// ////////////////////////////////////////////////////////////////////
// 心跳请求 0x00010001
type HeartBeatReq struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{0}
}
func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (dst *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(dst, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

func (m *HeartBeatReq) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

// 心跳回应 0x00010002
type HeartBeatRsp struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRsp) Reset()         { *m = HeartBeatRsp{} }
func (m *HeartBeatRsp) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRsp) ProtoMessage()    {}
func (*HeartBeatRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{1}
}
func (m *HeartBeatRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRsp.Unmarshal(m, b)
}
func (m *HeartBeatRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRsp.Marshal(b, m, deterministic)
}
func (dst *HeartBeatRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRsp.Merge(dst, src)
}
func (m *HeartBeatRsp) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRsp.Size(m)
}
func (m *HeartBeatRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRsp.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRsp proto.InternalMessageInfo

func (m *HeartBeatRsp) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

// ////////////////////////////////////////////////////////////////////
// 注册类
// ////////////////////////////////////////////////////////////////////
// 服务注册请求 0x00010003
type SvrRegReq struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	ProtocolType         *string  `protobuf:"bytes,2,req,name=ProtocolType" json:"ProtocolType,omitempty"`
	ChannelId            *string  `protobuf:"bytes,3,req,name=ChannelId" json:"ChannelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SvrRegReq) Reset()         { *m = SvrRegReq{} }
func (m *SvrRegReq) String() string { return proto.CompactTextString(m) }
func (*SvrRegReq) ProtoMessage()    {}
func (*SvrRegReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{2}
}
func (m *SvrRegReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SvrRegReq.Unmarshal(m, b)
}
func (m *SvrRegReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SvrRegReq.Marshal(b, m, deterministic)
}
func (dst *SvrRegReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SvrRegReq.Merge(dst, src)
}
func (m *SvrRegReq) XXX_Size() int {
	return xxx_messageInfo_SvrRegReq.Size(m)
}
func (m *SvrRegReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SvrRegReq.DiscardUnknown(m)
}

var xxx_messageInfo_SvrRegReq proto.InternalMessageInfo

func (m *SvrRegReq) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *SvrRegReq) GetProtocolType() string {
	if m != nil && m.ProtocolType != nil {
		return *m.ProtocolType
	}
	return ""
}

func (m *SvrRegReq) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

// 服务注册响应 0x00010004
type SvrRegRsp struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	RetCode              *int32   `protobuf:"varint,2,req,name=RetCode" json:"RetCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SvrRegRsp) Reset()         { *m = SvrRegRsp{} }
func (m *SvrRegRsp) String() string { return proto.CompactTextString(m) }
func (*SvrRegRsp) ProtoMessage()    {}
func (*SvrRegRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{3}
}
func (m *SvrRegRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SvrRegRsp.Unmarshal(m, b)
}
func (m *SvrRegRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SvrRegRsp.Marshal(b, m, deterministic)
}
func (dst *SvrRegRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SvrRegRsp.Merge(dst, src)
}
func (m *SvrRegRsp) XXX_Size() int {
	return xxx_messageInfo_SvrRegRsp.Size(m)
}
func (m *SvrRegRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SvrRegRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SvrRegRsp proto.InternalMessageInfo

func (m *SvrRegRsp) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *SvrRegRsp) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// 通道管理请求 0x00020001
type ChannelMgrReq struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	MgrType              *int32   `protobuf:"varint,2,req,name=MgrType" json:"MgrType,omitempty"`
	ChannelId            *string  `protobuf:"bytes,3,req,name=ChannelId" json:"ChannelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelMgrReq) Reset()         { *m = ChannelMgrReq{} }
func (m *ChannelMgrReq) String() string { return proto.CompactTextString(m) }
func (*ChannelMgrReq) ProtoMessage()    {}
func (*ChannelMgrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{4}
}
func (m *ChannelMgrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelMgrReq.Unmarshal(m, b)
}
func (m *ChannelMgrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelMgrReq.Marshal(b, m, deterministic)
}
func (dst *ChannelMgrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelMgrReq.Merge(dst, src)
}
func (m *ChannelMgrReq) XXX_Size() int {
	return xxx_messageInfo_ChannelMgrReq.Size(m)
}
func (m *ChannelMgrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelMgrReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelMgrReq proto.InternalMessageInfo

func (m *ChannelMgrReq) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *ChannelMgrReq) GetMgrType() int32 {
	if m != nil && m.MgrType != nil {
		return *m.MgrType
	}
	return 0
}

func (m *ChannelMgrReq) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

// 通道管理应答 0x00020002
type ChannelMgrRsp struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	RetCode              *int32   `protobuf:"varint,2,req,name=RetCode" json:"RetCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelMgrRsp) Reset()         { *m = ChannelMgrRsp{} }
func (m *ChannelMgrRsp) String() string { return proto.CompactTextString(m) }
func (*ChannelMgrRsp) ProtoMessage()    {}
func (*ChannelMgrRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{5}
}
func (m *ChannelMgrRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelMgrRsp.Unmarshal(m, b)
}
func (m *ChannelMgrRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelMgrRsp.Marshal(b, m, deterministic)
}
func (dst *ChannelMgrRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelMgrRsp.Merge(dst, src)
}
func (m *ChannelMgrRsp) XXX_Size() int {
	return xxx_messageInfo_ChannelMgrRsp.Size(m)
}
func (m *ChannelMgrRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelMgrRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelMgrRsp proto.InternalMessageInfo

func (m *ChannelMgrRsp) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *ChannelMgrRsp) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// 通道参数变更请求 0x00020003
type ChannelUpdateReq struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	ProtocolType         *string  `protobuf:"bytes,2,req,name=ProtocolType" json:"ProtocolType,omitempty"`
	ChannelId            *string  `protobuf:"bytes,3,req,name=ChannelId" json:"ChannelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUpdateReq) Reset()         { *m = ChannelUpdateReq{} }
func (m *ChannelUpdateReq) String() string { return proto.CompactTextString(m) }
func (*ChannelUpdateReq) ProtoMessage()    {}
func (*ChannelUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{6}
}
func (m *ChannelUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUpdateReq.Unmarshal(m, b)
}
func (m *ChannelUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUpdateReq.Marshal(b, m, deterministic)
}
func (dst *ChannelUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUpdateReq.Merge(dst, src)
}
func (m *ChannelUpdateReq) XXX_Size() int {
	return xxx_messageInfo_ChannelUpdateReq.Size(m)
}
func (m *ChannelUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUpdateReq proto.InternalMessageInfo

func (m *ChannelUpdateReq) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *ChannelUpdateReq) GetProtocolType() string {
	if m != nil && m.ProtocolType != nil {
		return *m.ProtocolType
	}
	return ""
}

func (m *ChannelUpdateReq) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

// 通道参数变更应答 0x00020004
type ChannelUpdateRsp struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	RetCode              *int32   `protobuf:"varint,2,req,name=RetCode" json:"RetCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUpdateRsp) Reset()         { *m = ChannelUpdateRsp{} }
func (m *ChannelUpdateRsp) String() string { return proto.CompactTextString(m) }
func (*ChannelUpdateRsp) ProtoMessage()    {}
func (*ChannelUpdateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{7}
}
func (m *ChannelUpdateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUpdateRsp.Unmarshal(m, b)
}
func (m *ChannelUpdateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUpdateRsp.Marshal(b, m, deterministic)
}
func (dst *ChannelUpdateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUpdateRsp.Merge(dst, src)
}
func (m *ChannelUpdateRsp) XXX_Size() int {
	return xxx_messageInfo_ChannelUpdateRsp.Size(m)
}
func (m *ChannelUpdateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUpdateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUpdateRsp proto.InternalMessageInfo

func (m *ChannelUpdateRsp) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *ChannelUpdateRsp) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// 信息发送请求 0x00020005
type GateWayMsgSendReq struct {
	SID                  *string                             `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	SrcPhone             *string                             `protobuf:"bytes,2,req,name=SrcPhone" json:"SrcPhone,omitempty"`
	MessageContent       *string                             `protobuf:"bytes,3,req,name=MessageContent" json:"MessageContent,omitempty"`
	ChannelType          *int32                              `protobuf:"varint,4,req,name=ChannelType" json:"ChannelType,omitempty"`
	ChannelId            *string                             `protobuf:"bytes,5,req,name=ChannelId" json:"ChannelId,omitempty"`
	ChannelGroupId       *string                             `protobuf:"bytes,6,req,name=ChannelGroupId" json:"ChannelGroupId,omitempty"`
	DateTime             *string                             `protobuf:"bytes,7,req,name=DateTime" json:"DateTime,omitempty"`
	SubmitId             *string                             `protobuf:"bytes,8,req,name=SubmitId" json:"SubmitId,omitempty"`
	Batchno              *string                             `protobuf:"bytes,9,req,name=Batchno" json:"Batchno,omitempty"`
	OperatorId           *string                             `protobuf:"bytes,10,req,name=OperatorId" json:"OperatorId,omitempty"`
	CustomerId           *string                             `protobuf:"bytes,11,req,name=CustomerId" json:"CustomerId,omitempty"`
	AccountId            *string                             `protobuf:"bytes,12,req,name=AccountId" json:"AccountId,omitempty"`
	CompanyId            *string                             `protobuf:"bytes,13,req,name=CompanyId" json:"CompanyId,omitempty"`
	SubmitWay            *int32                              `protobuf:"varint,14,req,name=SubmitWay" json:"SubmitWay,omitempty"`
	IsOtoSend            *int32                              `protobuf:"varint,15,req,name=IsOtoSend" json:"IsOtoSend,omitempty"`
	IsSmsResend          *int32                              `protobuf:"varint,16,req,name=IsSmsResend" json:"IsSmsResend,omitempty"`
	ReturnType           *int32                              `protobuf:"varint,17,req,name=ReturnType" json:"ReturnType,omitempty"`
	SmsData              *string                             `protobuf:"bytes,18,req,name=SmsData" json:"SmsData,omitempty"`
	PhoneList            []*GateWayMsgSendReq_PhoneListGroup `protobuf:"bytes,19,rep,name=PhoneList" json:"PhoneList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GateWayMsgSendReq) Reset()         { *m = GateWayMsgSendReq{} }
func (m *GateWayMsgSendReq) String() string { return proto.CompactTextString(m) }
func (*GateWayMsgSendReq) ProtoMessage()    {}
func (*GateWayMsgSendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{8}
}
func (m *GateWayMsgSendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateWayMsgSendReq.Unmarshal(m, b)
}
func (m *GateWayMsgSendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateWayMsgSendReq.Marshal(b, m, deterministic)
}
func (dst *GateWayMsgSendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateWayMsgSendReq.Merge(dst, src)
}
func (m *GateWayMsgSendReq) XXX_Size() int {
	return xxx_messageInfo_GateWayMsgSendReq.Size(m)
}
func (m *GateWayMsgSendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GateWayMsgSendReq.DiscardUnknown(m)
}

var xxx_messageInfo_GateWayMsgSendReq proto.InternalMessageInfo

func (m *GateWayMsgSendReq) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *GateWayMsgSendReq) GetSrcPhone() string {
	if m != nil && m.SrcPhone != nil {
		return *m.SrcPhone
	}
	return ""
}

func (m *GateWayMsgSendReq) GetMessageContent() string {
	if m != nil && m.MessageContent != nil {
		return *m.MessageContent
	}
	return ""
}

func (m *GateWayMsgSendReq) GetChannelType() int32 {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return 0
}

func (m *GateWayMsgSendReq) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

func (m *GateWayMsgSendReq) GetChannelGroupId() string {
	if m != nil && m.ChannelGroupId != nil {
		return *m.ChannelGroupId
	}
	return ""
}

func (m *GateWayMsgSendReq) GetDateTime() string {
	if m != nil && m.DateTime != nil {
		return *m.DateTime
	}
	return ""
}

func (m *GateWayMsgSendReq) GetSubmitId() string {
	if m != nil && m.SubmitId != nil {
		return *m.SubmitId
	}
	return ""
}

func (m *GateWayMsgSendReq) GetBatchno() string {
	if m != nil && m.Batchno != nil {
		return *m.Batchno
	}
	return ""
}

func (m *GateWayMsgSendReq) GetOperatorId() string {
	if m != nil && m.OperatorId != nil {
		return *m.OperatorId
	}
	return ""
}

func (m *GateWayMsgSendReq) GetCustomerId() string {
	if m != nil && m.CustomerId != nil {
		return *m.CustomerId
	}
	return ""
}

func (m *GateWayMsgSendReq) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *GateWayMsgSendReq) GetCompanyId() string {
	if m != nil && m.CompanyId != nil {
		return *m.CompanyId
	}
	return ""
}

func (m *GateWayMsgSendReq) GetSubmitWay() int32 {
	if m != nil && m.SubmitWay != nil {
		return *m.SubmitWay
	}
	return 0
}

func (m *GateWayMsgSendReq) GetIsOtoSend() int32 {
	if m != nil && m.IsOtoSend != nil {
		return *m.IsOtoSend
	}
	return 0
}

func (m *GateWayMsgSendReq) GetIsSmsResend() int32 {
	if m != nil && m.IsSmsResend != nil {
		return *m.IsSmsResend
	}
	return 0
}

func (m *GateWayMsgSendReq) GetReturnType() int32 {
	if m != nil && m.ReturnType != nil {
		return *m.ReturnType
	}
	return 0
}

func (m *GateWayMsgSendReq) GetSmsData() string {
	if m != nil && m.SmsData != nil {
		return *m.SmsData
	}
	return ""
}

func (m *GateWayMsgSendReq) GetPhoneList() []*GateWayMsgSendReq_PhoneListGroup {
	if m != nil {
		return m.PhoneList
	}
	return nil
}

type GateWayMsgSendReq_PhoneListGroup struct {
	SendId               *string  `protobuf:"bytes,1,opt,name=SendId" json:"SendId,omitempty"`
	IsNeedSend           *int32   `protobuf:"varint,2,opt,name=IsNeedSend" json:"IsNeedSend,omitempty"`
	VirtualStatus        *string  `protobuf:"bytes,3,opt,name=VirtualStatus" json:"VirtualStatus,omitempty"`
	ConvertStatus        *string  `protobuf:"bytes,4,opt,name=ConvertStatus" json:"ConvertStatus,omitempty"`
	MobilePhone          *string  `protobuf:"bytes,5,opt,name=MobilePhone" json:"MobilePhone,omitempty"`
	SmsContent           *string  `protobuf:"bytes,6,opt,name=SmsContent" json:"SmsContent,omitempty"`
	MobileCity           *string  `protobuf:"bytes,7,opt,name=MobileCity" json:"MobileCity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateWayMsgSendReq_PhoneListGroup) Reset()         { *m = GateWayMsgSendReq_PhoneListGroup{} }
func (m *GateWayMsgSendReq_PhoneListGroup) String() string { return proto.CompactTextString(m) }
func (*GateWayMsgSendReq_PhoneListGroup) ProtoMessage()    {}
func (*GateWayMsgSendReq_PhoneListGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{8, 0}
}
func (m *GateWayMsgSendReq_PhoneListGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateWayMsgSendReq_PhoneListGroup.Unmarshal(m, b)
}
func (m *GateWayMsgSendReq_PhoneListGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateWayMsgSendReq_PhoneListGroup.Marshal(b, m, deterministic)
}
func (dst *GateWayMsgSendReq_PhoneListGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateWayMsgSendReq_PhoneListGroup.Merge(dst, src)
}
func (m *GateWayMsgSendReq_PhoneListGroup) XXX_Size() int {
	return xxx_messageInfo_GateWayMsgSendReq_PhoneListGroup.Size(m)
}
func (m *GateWayMsgSendReq_PhoneListGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_GateWayMsgSendReq_PhoneListGroup.DiscardUnknown(m)
}

var xxx_messageInfo_GateWayMsgSendReq_PhoneListGroup proto.InternalMessageInfo

func (m *GateWayMsgSendReq_PhoneListGroup) GetSendId() string {
	if m != nil && m.SendId != nil {
		return *m.SendId
	}
	return ""
}

func (m *GateWayMsgSendReq_PhoneListGroup) GetIsNeedSend() int32 {
	if m != nil && m.IsNeedSend != nil {
		return *m.IsNeedSend
	}
	return 0
}

func (m *GateWayMsgSendReq_PhoneListGroup) GetVirtualStatus() string {
	if m != nil && m.VirtualStatus != nil {
		return *m.VirtualStatus
	}
	return ""
}

func (m *GateWayMsgSendReq_PhoneListGroup) GetConvertStatus() string {
	if m != nil && m.ConvertStatus != nil {
		return *m.ConvertStatus
	}
	return ""
}

func (m *GateWayMsgSendReq_PhoneListGroup) GetMobilePhone() string {
	if m != nil && m.MobilePhone != nil {
		return *m.MobilePhone
	}
	return ""
}

func (m *GateWayMsgSendReq_PhoneListGroup) GetSmsContent() string {
	if m != nil && m.SmsContent != nil {
		return *m.SmsContent
	}
	return ""
}

func (m *GateWayMsgSendReq_PhoneListGroup) GetMobileCity() string {
	if m != nil && m.MobileCity != nil {
		return *m.MobileCity
	}
	return ""
}

// 信息发送应答 0x00020006
type GateWayMsgSendRsp struct {
	SID                  *string  `protobuf:"bytes,1,req,name=SID" json:"SID,omitempty"`
	RetCode              *int32   `protobuf:"varint,2,req,name=RetCode" json:"RetCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateWayMsgSendRsp) Reset()         { *m = GateWayMsgSendRsp{} }
func (m *GateWayMsgSendRsp) String() string { return proto.CompactTextString(m) }
func (*GateWayMsgSendRsp) ProtoMessage()    {}
func (*GateWayMsgSendRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_f2021aeb03028bf2, []int{9}
}
func (m *GateWayMsgSendRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateWayMsgSendRsp.Unmarshal(m, b)
}
func (m *GateWayMsgSendRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateWayMsgSendRsp.Marshal(b, m, deterministic)
}
func (dst *GateWayMsgSendRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateWayMsgSendRsp.Merge(dst, src)
}
func (m *GateWayMsgSendRsp) XXX_Size() int {
	return xxx_messageInfo_GateWayMsgSendRsp.Size(m)
}
func (m *GateWayMsgSendRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GateWayMsgSendRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GateWayMsgSendRsp proto.InternalMessageInfo

func (m *GateWayMsgSendRsp) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *GateWayMsgSendRsp) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func init() {
	proto.RegisterType((*HeartBeatReq)(nil), "gatewaymsg.HeartBeatReq")
	proto.RegisterType((*HeartBeatRsp)(nil), "gatewaymsg.HeartBeatRsp")
	proto.RegisterType((*SvrRegReq)(nil), "gatewaymsg.SvrRegReq")
	proto.RegisterType((*SvrRegRsp)(nil), "gatewaymsg.SvrRegRsp")
	proto.RegisterType((*ChannelMgrReq)(nil), "gatewaymsg.ChannelMgrReq")
	proto.RegisterType((*ChannelMgrRsp)(nil), "gatewaymsg.ChannelMgrRsp")
	proto.RegisterType((*ChannelUpdateReq)(nil), "gatewaymsg.ChannelUpdateReq")
	proto.RegisterType((*ChannelUpdateRsp)(nil), "gatewaymsg.ChannelUpdateRsp")
	proto.RegisterType((*GateWayMsgSendReq)(nil), "gatewaymsg.GateWayMsgSendReq")
	proto.RegisterType((*GateWayMsgSendReq_PhoneListGroup)(nil), "gatewaymsg.GateWayMsgSendReq.PhoneListGroup")
	proto.RegisterType((*GateWayMsgSendRsp)(nil), "gatewaymsg.GateWayMsgSendRsp")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_gateway_f2021aeb03028bf2) }

var fileDescriptor_gateway_f2021aeb03028bf2 = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0x26, 0x4d, 0x93, 0x74, 0xa7, 0x4d, 0x4d, 0x47, 0x90, 0xa1, 0x88, 0x2c, 0x41, 0x24, 0x07,
	0xc9, 0xc1, 0x8b, 0x07, 0x41, 0xb1, 0x1b, 0xa8, 0x2b, 0xc6, 0x96, 0xdd, 0x6a, 0xf1, 0x24, 0xd3,
	0xec, 0x73, 0xb3, 0x90, 0xdd, 0x59, 0x67, 0x66, 0x2b, 0xfb, 0x8f, 0x7b, 0xf2, 0x20, 0xf3, 0x63,
	0x7f, 0xa5, 0x01, 0xc9, 0xc1, 0x5b, 0xde, 0xf7, 0x7d, 0x33, 0xef, 0xfb, 0xde, 0x9b, 0x0d, 0x1a,
	0xc7, 0x54, 0xc2, 0x2f, 0x5a, 0xce, 0x73, 0xce, 0x24, 0xc3, 0xc8, 0x96, 0xa9, 0x88, 0xa7, 0x2e,
	0x3a, 0xf9, 0x00, 0x94, 0xcb, 0x0b, 0xa0, 0x32, 0x80, 0x9f, 0x78, 0x82, 0xfa, 0xa1, 0xbf, 0x20,
	0x3d, 0xf7, 0x60, 0xe6, 0x04, 0xea, 0x67, 0x57, 0x21, 0xf2, 0x1d, 0x8a, 0xef, 0xc8, 0x09, 0xef,
	0x79, 0x00, 0xf1, 0xce, 0x0b, 0xf0, 0x14, 0x9d, 0x5c, 0xab, 0xbe, 0x2b, 0xb6, 0xb9, 0x29, 0x73,
	0x20, 0x07, 0x9a, 0xea, 0x60, 0xf8, 0x29, 0x72, 0xbc, 0x35, 0xcd, 0x32, 0xd8, 0xf8, 0x11, 0xe9,
	0x6b, 0x41, 0x03, 0x4c, 0x5f, 0xd7, 0x0d, 0x76, 0xf5, 0xc7, 0x04, 0x8d, 0x02, 0x90, 0x1e, 0x8b,
	0xcc, 0xdd, 0x83, 0xa0, 0x2a, 0xa7, 0xdf, 0xd0, 0xd8, 0xde, 0xb2, 0x8c, 0xf9, 0x6e, 0x77, 0x04,
	0x8d, 0x96, 0x31, 0xaf, 0x8d, 0x0d, 0x82, 0xaa, 0xfc, 0x87, 0xa7, 0x37, 0x9d, 0xab, 0xf7, 0xf4,
	0xf5, 0x03, 0x4d, 0xec, 0xe1, 0x2f, 0x79, 0x44, 0x25, 0xfc, 0xaf, 0xc1, 0xbd, 0xdd, 0xee, 0xb3,
	0xa7, 0xcf, 0x3f, 0x43, 0x74, 0x76, 0x49, 0x25, 0xdc, 0xd2, 0x72, 0x29, 0xe2, 0x10, 0xb2, 0x68,
	0xb7, 0xd3, 0x73, 0x74, 0x14, 0xf2, 0xd5, 0xf5, 0x9a, 0x65, 0x95, 0xcb, 0xba, 0xc6, 0x2f, 0xd0,
	0xe9, 0x12, 0x84, 0xa0, 0x31, 0x78, 0x2c, 0x93, 0x90, 0x49, 0x6b, 0x73, 0x0b, 0xc5, 0x2e, 0x3a,
	0xb6, 0x5e, 0x75, 0xd8, 0x43, 0xed, 0xa4, 0x0d, 0x75, 0xb3, 0x0e, 0xb6, 0xb2, 0xaa, 0x3e, 0xb6,
	0xb8, 0xe4, 0xac, 0xc8, 0xfd, 0x88, 0x0c, 0x4d, 0x9f, 0x2e, 0xaa, 0xbc, 0x2e, 0xa8, 0x84, 0x9b,
	0x24, 0x05, 0x32, 0x32, 0x5e, 0xab, 0x5a, 0xe7, 0x28, 0xee, 0xd2, 0x44, 0xfa, 0x11, 0x39, 0xb2,
	0x39, 0x6c, 0xad, 0xa6, 0x74, 0x41, 0xe5, 0x6a, 0x9d, 0x31, 0xe2, 0x68, 0xaa, 0x2a, 0xf1, 0x33,
	0x84, 0xae, 0x72, 0xe0, 0x54, 0x32, 0xee, 0x47, 0x04, 0x69, 0xb2, 0x85, 0x28, 0xde, 0x2b, 0x84,
	0x64, 0x29, 0x28, 0xfe, 0xd8, 0xf0, 0x0d, 0xa2, 0x72, 0xbd, 0x5f, 0xad, 0x58, 0x91, 0xa9, 0xb6,
	0x27, 0x26, 0x57, 0x0d, 0xe8, 0xd4, 0x2c, 0xcd, 0x69, 0x56, 0xfa, 0x11, 0x19, 0xdb, 0xd4, 0x15,
	0xa0, 0x58, 0xe3, 0xf0, 0x96, 0x96, 0xe4, 0x54, 0xcf, 0xac, 0x01, 0x14, 0xeb, 0x8b, 0x2b, 0xc9,
	0xd4, 0xe6, 0xc8, 0x23, 0xc3, 0xd6, 0x80, 0x9a, 0xb8, 0x2f, 0xc2, 0x54, 0x04, 0x20, 0x14, 0x3f,
	0x31, 0x13, 0x6f, 0x41, 0xca, 0x79, 0x00, 0xb2, 0xe0, 0x99, 0x5e, 0xc9, 0x99, 0x16, 0xb4, 0x10,
	0x35, 0x93, 0x30, 0x15, 0x0b, 0x2a, 0x29, 0xc1, 0x66, 0x26, 0xb6, 0xc4, 0x1f, 0x91, 0xa3, 0xd7,
	0xff, 0x29, 0x11, 0x92, 0x3c, 0x76, 0xfb, 0xb3, 0xe3, 0x57, 0x2f, 0xe7, 0xcd, 0xff, 0xce, 0xfc,
	0xc1, 0xab, 0x9a, 0xd7, 0x72, 0xbd, 0xa8, 0xa0, 0x39, 0x7e, 0xfe, 0xbb, 0x87, 0x4e, 0xbb, 0x2c,
	0x7e, 0x82, 0x86, 0xea, 0x9c, 0x1f, 0x91, 0x9e, 0xdb, 0x9b, 0x39, 0x81, 0xad, 0x94, 0x61, 0x5f,
	0x7c, 0x06, 0x88, 0x74, 0xe2, 0x03, 0xb7, 0xa7, 0x0c, 0x37, 0x08, 0x7e, 0x8e, 0xc6, 0x5f, 0x13,
	0x2e, 0x0b, 0xba, 0x09, 0x25, 0x95, 0x85, 0x20, 0x7d, 0x7d, 0xbc, 0x0b, 0x2a, 0x95, 0xc7, 0xb2,
	0x7b, 0xe0, 0xd2, 0xaa, 0x0e, 0x8d, 0xaa, 0x03, 0xaa, 0xf1, 0x2d, 0xd9, 0x5d, 0xb2, 0x01, 0xf3,
	0xee, 0x07, 0x5a, 0xd3, 0x86, 0x94, 0x9b, 0x30, 0x15, 0xd5, 0xb3, 0x1f, 0x6a, 0x41, 0x0b, 0x51,
	0xbc, 0x91, 0x7b, 0x89, 0x2c, 0xc9, 0xc8, 0xf0, 0x0d, 0x32, 0x7d, 0xf7, 0xe0, 0xeb, 0xdb, 0xef,
	0xfb, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x88, 0x12, 0x42, 0xf9, 0x05, 0x00, 0x00,
}
